version: '3'

services:
  python3:
    container_name: django-app
    build: ./app
    working_dir: /root/
    volumes:
      - ./app:/root/app
    ports:
      - 8000:8000
    tty: true
    restart: always